name: CI

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        platform:
        - os: ubuntu-latest
        - os: macos-latest
      fail-fast: false

    runs-on: ${{ matrix.platform.os }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v1.1.0

      - name: install deps
        run: |
          brew install tree
          brew install kcov

      - name: Run Tests
        run: COV=1 bash test/run.sh

      - name: Deploy coverage report
        if: ${{ matrix.platform.os }} == 'macos-latest'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./coverage-all
          user_name: 'nave-kcov-actions-bot'
          user_email: 'nave-kcov-actions-bot@example.com'
